version: "3"

services:
  webdev:
    image: sharp6292/codeserver-webdev

    volumes:
      - mcaq_dev:/dev/live
      - mcaq_privdev:/dev/privlive

    restart: always

  vscode:
    hostname: vscode
    image: sharp6292/codeserver:latest
    environment:
      - PASSWORD=${VSCODEPASS}

    volumes:
      - "mcaq_projects:/home/coder/project"
      - "mcaq_home:/home/coder"
      - "mcaq_dev:/dev/live"
      - "mcaq_privdev:/dev/privlive"
      - "/var/run/docker.sock:/var/run/docker.sock"

    command: code-server --auth password
    restart: always


volumes:
  mcaq_projects:
    external: True
  mcaq_home:
    external: True
  mcaq_dev:
    external: True
  mcaq_privdev:
    external: True

networks:
    default:
        external:
            name: sharpnet
