version: 2.1

jobs:
  create:
    docker:
      - image: python:3.7.3-slim-stretch

    steps:
      - checkout

      - run:
          name: Create Build Files
          command: |
            mkdir workspace
            cd dockerfiles

            mkdir builds
            python build.py
            cd ..

            cp -a ./dockerfiles/builds/. ./workspace

      - persist_to_workspace:
          root: .
          paths:
            - ./workspace

  build:
    docker:
      - image: docker:stable

    parallelism: 4

    steps:
      - checkout

      - setup_remote_docker

      - attach_workspace:
          at: .

      - run:
          name: "Build"
          command: |
            sh ./workspace/build-${CIRCLE_NODE_INDEX}.sh

  deploy:
    docker:
      - image: cimg/base:2020.01

    steps:
      - checkout

      - run:
          name: "Install SharpCD"
          command: |
            wget https://github.com/Sharpz7/sharpcd/releases/download/0.1.0/linux.tar.gz
            sudo tar -C /usr/local/bin/ -zxvf linux.tar.gz
            rm -r linux.tar.gz

            chmod u+x /usr/local/bin/sharpcd

      - run:
          name: "Setup Env"
          command: |
            echo "VSCODEPASS=${VSCODEPASS}" > .env

      - run:
          name: "SharpCD Deploy"
          command: |
            sharpcd --secret ${SHARPCD_SECRET}

workflows:
  version: 2
  workflow:
    jobs:
      - create

      - build:
          requires:
            - create
          context: General

      - deploy:
          context: General
          requires:
            - build

          filters:
            branches:
              only: main